<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-JFR5O47" failures="2" tests="12" name="org.vtiger.practice.RetryAnalyzerPractice" time="0.062" errors="0" timestamp="2022-07-27T12:47:51 IST" skipped="10">
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.001">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.002">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.002">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.005">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.002">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.001">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.006">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.006">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at org.vtiger.practice.RetryAnalyzerPractice.retryAnalyzerPractice(RetryAnalyzerPractice.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.029">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.004">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.002">
    <skipped/>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
  <testcase classname="org.vtiger.practice.RetryAnalyzerPractice" name="retryAnalyzerPractice" time="0.002">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at org.vtiger.practice.RetryAnalyzerPractice.retryAnalyzerPractice(RetryAnalyzerPractice.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- retryAnalyzerPractice -->
  <system-out/>
</testsuite> <!-- org.vtiger.practice.RetryAnalyzerPractice -->
